### ISSUE TITLE
could you share JetPack-L4T-3.1-linux-x64.run?

### ISSUE THREAD

**Issue by yangyangcv** [KleinYuan/tx2-flash#1]
the download link in nvidia's official website is down :( could you kindly share the JetPack-L4T-3.1-linux-x64.run file? thanks in advance.   yangyangcv@gmail.com

**Comment by KleinYuan** [comment]
@yangyangcv 
I think you can download that from their website.
Directly emailing you that package may conflict with their license and therefore I still suggest you download it on your own.

**Comment by KleinYuan** [comment]
Not really an issue. Close
